### ISSUE TITLE
[1.12.2] Dedicated Server Crash

### ISSUE THREAD

**Issue by kwpugh** [winnetrie83/timsexpansionmod#1]
Crash Report: https://gist.github.com/kwpugh/22607ca42618c4ab6b7fb32fc5c44249

Forge: 14.23.2.2625 
Mod:  tem-3.0.jar

Only crashes when new chunks are loaded.

**Comment by winnetrie83** [comment]
Thank you for reporting. I'm working on a fix. It appears that getBiomeName has turned to clientsided.

**Comment by winnetrie83** [comment]
Issue has been fixed. Now using the proper method.
New version has been uploaded to curse
[Fix](https://github.com/winnetrie83/timsexpansionmod/blob/61e7cf1cf11dc178606da3cb326dcf88dc255da6/main/java/com/winnetrie/timsexpansionmod/world/ModWorldGenerator.java#L67)
